version: "3.9"
services:
  gradcam:
    build: ./gradcam
    ports:
      - "8000:8000"
    volumes:
      - ./gradcam:/app
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    depends_on:
      - "gradcam"